### ISSUE TITLE
使用 Vim 搭建 Rust 开发环境 | SpaceVim

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim-comments#56]
https://spacevim.org/cn/use-vim-as-a-rust-ide/

**Comment by sharefantasy** [comment]
lsp那里为什么是php？应该是rust吧？

**Comment by wsdjeg** [comment]
感谢，这个地方写错了，后面更新改正过来。

**Comment by erasin** [comment]
如何使用 rust 二代lsp , [rust-analyzer](https://rust-analyzer.github.io/manual.html), 我按照官方给的文档，设置 coc 和 LanguageClient-neovim 配置都是不起作用。

**Comment by wsdjeg** [comment]
首先，确保有 `rust-analyzer` 可执行命令，然后启用 lsp 模块：

```toml
[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
    rust = ["rust-analyzer"]
```
